version: '3.9'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./.docker/images/nginx/conf.d/:/etc/nginx/conf.d/
            - ./:/var/www
        networks:
            - app-network
        ports:
            -   "80:80"
    php:
        build:
            context: ./.docker/images/php
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    mysql:
        image: mysql
        volumes:
            - ./.docker/.data/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        ports:
            - "${DB_DC_PORT}:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
